png(file = "./project1/plot4.png")
par(mfrow=c(2, 2), mar=c(4, 4, 2 , 1))
plot(householdPowerConsumption$dateTime, householdPowerConsumption$Global_active_power, type="l", ylab="Global Active Power", xlab="")
plot(householdPowerConsumption$dateTime, householdPowerConsumption$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(householdPowerConsumption$dateTime, householdPowerConsumption$Sub_metering_1, type="n", ylab="Energy Sub Metering", xlab="")
lines(householdPowerConsumption$dateTime, householdPowerConsumption$Sub_metering_1, col="black")
lines(householdPowerConsumption$dateTime, householdPowerConsumption$Sub_metering_2, col="red")
lines(householdPowerConsumption$dateTime, householdPowerConsumption$Sub_metering_3, col="blue")
legend("topright",  lty=1, bty="n", col=c("black", "blue", "red"), cex=0.7, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(householdPowerConsumption$dateTime, householdPowerConsumption$Global_reactive_power, type="l", ylab="Global_reactive_power", xlab="datetime")
dev.off()